config/routes.rb
Kinney::Engine.routes.draw do

  post "tracker/track", :to => 'tracker#track'
  # match "tracker/analyze/:video", :to => 'tracker#analyze', :via => :get, :as => 'tracker_analyze'

  get "search", :as => :search, :to => 'search#index'
  get "about", :as => :about, :to => 'pages#about'

  get 'giving', :as => :giving, :to => 'pages#giving'
  # get 'contact' => 'contact#new', :as => 'contact'
  # post 'contact' => 'contact#create', :as => 'contact'

  root :to => 'pages#home'

  resources :people, :only => [:index, :show]
  resources :topics, :only => [:index, :show]
  resources :clips,  :only => [:index, :show], :path => '/videos'

  # mount Ckeditor::Engine => "/ckeditor"

  get "/sitemap" => "sitemap#index", :as => :sitemap,
    :defaults => {:format => :xml}

end

app/models/kinney/admin_user.rb
class Kinney::AdminUser < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create { |admin| admin.send_reset_password_instructions }
  def password_required?
    new_record? ? false : super
  end
end

# == Schema Information
#
# Table name: kinney_admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

app/models/kinney/clip.rb
module Kinney
  class Clip < ActiveRecord::Base
    include Kinney::Concerns::Models::Clip
  end
end

# == Schema Information
#
# Table name: kinney_clips
#
#  id              :integer          not null, primary key
#  filename        :string(255)
#  title           :string(255)
#  quotes          :text
#  top_pick        :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  slug            :string(255)
#  duration        :integer
#  interview_date  :date
#  description     :text
#  featured        :boolean
#  interview_place :string(255)
#  media_type_id   :integer
#

app/models/kinney/clip_person.rb
module Kinney
  class ClipPerson < ActiveRecord::Base
    belongs_to :person
    belongs_to :clip
  end
end

# == Schema Information
#
# Table name: kinney_clip_people
#
#  id         :integer          not null, primary key
#  person_id  :integer
#  clip_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/clip_topic.rb
module Kinney
  class ClipTopic < ActiveRecord::Base
    belongs_to :clip
    belongs_to :topic
  end
end

# == Schema Information
#
# Table name: kinney_clip_topics
#
#  id         :integer          not null, primary key
#  clip_id    :integer
#  topic_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/image.rb
module Kinney
  class Image < ActiveRecord::Base
    include Kinney::Concerns::Models::Image

    # This method should now be defined in the image override which is installed as part of the kinney:install generator
    # def external_url
    #   false
    # end

  end
end

# == Schema Information
#
# Table name: kinney_images
#
#  id         :integer          not null, primary key
#  filename   :string(255)
#  top_pick   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/interviewer_person.rb
module Kinney
  class InterviewerPerson < ActiveRecord::Base
    belongs_to :clip
    belongs_to :person
  end
end

app/models/kinney/media_type.rb
module Kinney
  class MediaType < ActiveRecord::Base
    include Kinney::Concerns::Models::MediaType
  end
end

# == Schema Information
#
# Table name: kinney_media_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/models/kinney/person.rb
module Kinney
  class Person < ActiveRecord::Base
    include Kinney::Concerns::Models::Person
  end
end

# == Schema Information
#
# Table name: kinney_people
#
#  id               :integer          not null, primary key
#  first_name       :string(255)
#  middle_name      :string(255)
#  last_name        :string(255)
#  nickname         :string(255)
#  biography        :text
#  accomplishments  :text
#  activities       :text
#  currently        :text
#  citations        :text
#  graduating_class :integer
#  term             :text
#  term_date_ranges :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  slug             :string(255)
#  name_suffix      :string(255)
#  location         :string(255)
#  honorary         :string(255)
#

app/models/kinney/person_image.rb
module Kinney
  class PersonImage < ActiveRecord::Base
    belongs_to :person
    belongs_to :image
  end
end

# == Schema Information
#
# Table name: kinney_person_images
#
#  id         :integer          not null, primary key
#  person_id  :integer
#  image_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/topic.rb
module Kinney
  class Topic < ActiveRecord::Base
    include Kinney::Concerns::Models::Topic
  end
end

# == Schema Information
#
# Table name: kinney_topics
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string(255)
#  description :text
#

app/models/kinney/tracker.rb
module Kinney
  class Tracker < ActiveRecord::Base
    serialize :seconds, Array
  end
end

# == Schema Information
#
# Table name: kinney_trackers
#
#  id         :integer          not null, primary key
#  uuid       :string(255)
#  seconds    :text
#  video      :string(255)
#  site       :string(255)
#  time       :date
#  session    :string(255)
#  sessioned  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/kinney/clips_controller.rb
module Kinney
  class ClipsController < KinneyController
    include Kinney::Concerns::Controllers::ClipsController
  end
end

app/controllers/kinney/kinney_controller.rb
module Kinney
  class KinneyController < ApplicationController
    helper Kinney::Engine.helpers

    before_filter :gather_topics_for_navigation

    def gather_topics_for_navigation
      @navigation_topics = Topic.with_clips
    end

  end
end

app/controllers/kinney/pages_controller.rb
module Kinney
  class PagesController < KinneyController
    include Kinney::Concerns::Controllers::PagesController
  end
end

app/controllers/kinney/people_controller.rb
module Kinney
  class PeopleController < KinneyController
    include Kinney::Concerns::Controllers::PeopleController
  end
end

app/controllers/kinney/search_controller.rb
module Kinney
  class SearchController < KinneyController
    include Kinney::Concerns::Controllers::SearchController
  end
end

app/controllers/kinney/sitemap_controller.rb
module Kinney
  class SitemapController < KinneyController
    layout nil

    def index
      @people = Person.select([:id, :slug, :created_at, :updated_at])
      @clips  = Clip.all
      headers["Content-Type"] = "text/xml"
      respond_to do |format|
        format.xml{render :layout => false}
      end
    end
  end
end

app/controllers/kinney/topics_controller.rb
module Kinney
  class TopicsController < KinneyController
    include Kinney::Concerns::Controllers::ClipTopicsController
  end
end

app/controllers/kinney/tracker_controller.rb
module Kinney
  class TrackerController < KinneyController

    def track
      if request.xhr?
        data = params["tracker"].dup
        data["session"] = session[:session_id]
        tracker = Tracker.new data.permit(params_permitted)
        tracker.save
        head :ok
      end
    end

    private

    def params_permitted
      [{:seconds => [:start, :end]}, :session, :sessioned, :site, :time, :uuid, :video]
    end

  end
end

app/helpers/kinney/clip_helper.rb
module Kinney
  module ClipHelper
    # FIXME: there has to be a better way to do this so that reloading works!
    # include ::KinneyClipHelper

    def duration_pretty(clip)
      "(#{clip.duration_pretty})" if !clip.duration.blank?
    end


    def download_button(clip)
      link_to(clip.mp4, :class => ['btn', 'btn-lg', 'btn-default'], :id => 'download_mp4') do
        "<i class='icon-arrow-down'></i> #{t 'kinney.clips.show.download_mp4'}".html_safe
      end
    end

    # TODO: once we have VTT for everything change this and make VTT's manditory
    def vtt_button(clip)
      begin
        client = HTTPClient.new
        response = client.head(clip.vtt)
        link_to_options = {:class => 'btn btn-lg btn-default', :id => 'download_vtt'}
        if response.status != 200
          link_to_options.merge!(:style => 'display:none')
        end
        link_to(clip.vtt, link_to_options) do
            "<i class='icon-arrow-down'></i> #{t :download_transcript}".html_safe
          end
      rescue
      end
    end

    def jump_time(timestamp)
      time_parts = timestamp.split(':')
      seconds = time_parts.pop
      minutes = time_parts.pop
      hours   = time_parts.first if !time_parts.blank?
      total_seconds = hours.to_i.hours.seconds
      total_seconds += minutes.to_i.minutes.seconds
      total_seconds += seconds.split('.').first.to_i
    end

    def topic_li_class(topic)
      current_page?(topic_path(topic)) ? 'active' : ''
    end

  end
end

app/views/kinney/_clip_link.html.erb
<%= link_to(clip, clip.video_switcher_params.merge(:class => [:thumbnail, :thumbnail_video])) do %>
  <div class="thumbnail_image clip_thumbnail">
    <%= image_tag clip.png, :alt => clip.title %>
    <% if !clip.duration.blank? %>
      <span class="duration label"><%= clip.duration_pretty %></span>
    <% end -%>
  </div>
  <%= render partial: '/kinney/clip_link_caption', locals: {clip: clip} %>
<% end -%>

app/views/kinney/_clip_link_caption.html.erb
<div class="caption">
  <%= render partial: '/kinney/clip_link_caption_names_and_title', locals: {clip: clip} %>
</div>

app/views/kinney/_clip_link_caption_names_and_title.html.erb
<div class="name"><%= clip.full_people_names %></div>
<span class="title"><%= clip.title %></span>

app/views/kinney/_contact.html.erb
<div class="row">
  <div class="col-md-6">
    <h2><%= t 'kinney.contact.title' %></h2>
    <table class="table table-striped">
      <tbody>
        <tr>
          <td><%= t 'kinney.contact.phone_number' %></td>
          <td>I'm not giving you my phone number. You'll probably want to replace this whole partial at app/views/kinney/contact.html.erb.</td>
        </tr>
        <tr>
          <td><%= t 'kinney.contact.email' %></td>
          <td><%= mail_to 'jronallo@gmail.com' %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/kinney/_link_to_full_transcript.html.erb
<p>Override the partial /kinney/_link_to_full_transcript.html.erb</p>

app/views/kinney/_pull_quotes.html.erb
<div id="pull_quotes">
  <% if !clip.quotes.blank? %>
    <%= render 'clips/quotes', :mustache => {:quotes => clip.quotes}%>
  <% end -%>
</div>

app/views/kinney/_search_form.html.erb
<%= form_tag kinney.search_path, :method => :get, :class => ['navbar-form', 'navbar-left'], :role => 'search' do %>
  <div class="form-group">
    <%= text_field_tag :q, params[:q], :class => 'form-control', :placeholder => t('kinney.search.placeholder') %>
  </div>
  <%= submit_tag t('kinney.search.submit_text'), :name => nil, :class => ['btn btn-default'] %>
<% end %>

app/views/kinney/_short_profile_and_pull_quotes.html.erb
<%# clip %>
<%= render :partial => "/pull_quotes", :locals => {:clip => clip} %>
<div id="short_profiles">
  <% clip.people.each do |person| %>
    <%= render 'people/short_profile',
      :mustache => {:full_name => person.full_name, :short_bio => person.short_bio,
        :person_href => person_path(person), :last_name => person.last_name} %>
  <% end -%>
</div>

app/views/kinney/_video.html.erb
<div id="video_container">
  <video width="480" height="272" style="width:100%;height:100%;" poster="<%= clip.png %>"
    controls="true" preload="true" id="<%= clip.filename %>"
    data-video-clip-url="<%= kinney.clip_url(clip) %>">

    <source src="<%= clip.mp4 %>" type="video/mp4" />
    <source src="<%= clip.webm %>" type="video/webm" />

    <track label="English subtitles" kind="subtitles" srclang="en" src="<%= clip.vtt %>"
      id="subtitles">
    <!--<track srclang="en" kind="chapters" src="<%= clip.chapters %>" />-->

    <object type="application/x-shockwave-flash" data="<%= asset_path 'mediaelement_rails/flashmediaelement.swf' %>">
        <param name="movie" value="<%= asset_path 'mediaelement_rails/flashmediaelement.swf' %>" />
        <param name="flashvars"
          value="controls=true&amp;preload=true&amp;poster=<%= clip.png %>&amp;file=<%= clip.mp4 %>" />
        <img src="<%= clip.png %>"  title="No video playback capabilities. Use the download link below." />
    </object>
  </video>
</div>

app/views/kinney/_video_profiles_thumbs.html.erb
<%# FIXME: Is this used anymore? %>
<h2><%= link_to title, people_path %></h2>
<ul class="thumbnails more_people">
  <% @people.each do |person| %>
    <li class="col-md-3">
    <%= link_to(person, :class => :thumbnail) do %>
      <%= image_tag person.clips.first.png, :alt => person.clips.first.title %>
        <div class="caption">
          <%= person.full_name %>
        </div>
    <% end -%>
    </li>
  <% end -%>
</ul>

app/views/kinney/_video_topics.html.erb
<div class="list-group topics">
  <% @topics_with_clips.each do |topic| %>
    <%= link_to topic, class: [topic.friendly_id, :'list-group-item'] do %>
      <i></i> <%= topic.name %>
    <% end -%>
  <% end -%>
</div>

app/views/kinney/_webvtt.html.erb
<% if @webvtt %>
  
  <h2><%= t 'kinney.transcript.title' %></h2>
  <%#= vtt_button(@clip) %>
  <table class="table table-striped" id="transcript_table">
    <thead>
      <tr>
        <th><%= t 'kinney.transcript.text' %></th>
        <th><%= t 'kinney.transcript.timestamp' %></th>
      </tr>
    </thead>
    <tbody>
      <% @webvtt.cues.each do |cue| %>
        <tr>
          <td><%= cue.text %></td>
          <td><%= link_to cue.start, '', :class => 'transcript_jump', :'data-video-jump-time' => jump_time(cue.start) %> - <%= cue.end %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>

  <%= render partial: "/kinney/link_to_full_transcript" %>
    
<% end -%>