config/routes.rb
Kinney::Engine.routes.draw do

  post "tracker/track", :to => 'tracker#track'
  # match "tracker/analyze/:video", :to => 'tracker#analyze', :via => :get, :as => 'tracker_analyze'

  get "search", :as => :search, :to => 'search#index'
  get "about", :as => :about, :to => 'pages#about'

  get 'giving', :as => :giving, :to => 'pages#giving'
  # get 'contact' => 'contact#new', :as => 'contact'
  # post 'contact' => 'contact#create', :as => 'contact'

  root :to => 'pages#home'

  resources :people, :only => [:index, :show]
  resources :topics, :only => [:index, :show]
  resources :clips,  :only => [:index, :show], :path => '/videos'

  # mount Ckeditor::Engine => "/ckeditor"

  get "/sitemap" => "sitemap#index", :as => :sitemap,
    :defaults => {:format => :xml}

end

app/models/kinney/admin_user.rb
class Kinney::AdminUser < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create { |admin| admin.send_reset_password_instructions }
  def password_required?
    new_record? ? false : super
  end
end

# == Schema Information
#
# Table name: kinney_admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

app/models/kinney/clip.rb
module Kinney
  class Clip < ActiveRecord::Base
    include Kinney::Concerns::Models::Clip
  end
end

# == Schema Information
#
# Table name: kinney_clips
#
#  id              :integer          not null, primary key
#  filename        :string(255)
#  title           :string(255)
#  quotes          :text
#  top_pick        :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  slug            :string(255)
#  duration        :integer
#  interview_date  :date
#  description     :text
#  featured        :boolean
#  interview_place :string(255)
#  media_type_id   :integer
#

app/models/kinney/clip_person.rb
module Kinney
  class ClipPerson < ActiveRecord::Base
    belongs_to :person
    belongs_to :clip
  end
end

# == Schema Information
#
# Table name: kinney_clip_people
#
#  id         :integer          not null, primary key
#  person_id  :integer
#  clip_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/clip_topic.rb
module Kinney
  class ClipTopic < ActiveRecord::Base
    belongs_to :clip
    belongs_to :topic
  end
end

# == Schema Information
#
# Table name: kinney_clip_topics
#
#  id         :integer          not null, primary key
#  clip_id    :integer
#  topic_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/image.rb
module Kinney
  class Image < ActiveRecord::Base
    include Kinney::Concerns::Models::Image

    # This method should now be defined in the image override which is installed as part of the kinney:install generator
    # def external_url
    #   false
    # end

  end
end

# == Schema Information
#
# Table name: kinney_images
#
#  id         :integer          not null, primary key
#  filename   :string(255)
#  top_pick   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/interviewer_person.rb
module Kinney
  class InterviewerPerson < ActiveRecord::Base
    belongs_to :clip
    belongs_to :person
  end
end

app/models/kinney/media_type.rb
module Kinney
  class MediaType < ActiveRecord::Base
    include Kinney::Concerns::Models::MediaType
  end
end

# == Schema Information
#
# Table name: kinney_media_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/models/kinney/person.rb
module Kinney
  class Person < ActiveRecord::Base
    include Kinney::Concerns::Models::Person
  end
end

# == Schema Information
#
# Table name: kinney_people
#
#  id               :integer          not null, primary key
#  first_name       :string(255)
#  middle_name      :string(255)
#  last_name        :string(255)
#  nickname         :string(255)
#  biography        :text
#  accomplishments  :text
#  activities       :text
#  currently        :text
#  citations        :text
#  graduating_class :integer
#  term             :text
#  term_date_ranges :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  slug             :string(255)
#  name_suffix      :string(255)
#  location         :string(255)
#  honorary         :string(255)
#

app/models/kinney/person_image.rb
module Kinney
  class PersonImage < ActiveRecord::Base
    belongs_to :person
    belongs_to :image
  end
end

# == Schema Information
#
# Table name: kinney_person_images
#
#  id         :integer          not null, primary key
#  person_id  :integer
#  image_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/kinney/topic.rb
module Kinney
  class Topic < ActiveRecord::Base
    include Kinney::Concerns::Models::Topic
  end
end

# == Schema Information
#
# Table name: kinney_topics
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string(255)
#  description :text
#

app/models/kinney/tracker.rb
module Kinney
  class Tracker < ActiveRecord::Base
    serialize :seconds, Array
  end
end

# == Schema Information
#
# Table name: kinney_trackers
#
#  id         :integer          not null, primary key
#  uuid       :string(255)
#  seconds    :text
#  video      :string(255)
#  site       :string(255)
#  time       :date
#  session    :string(255)
#  sessioned  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/kinney/clips_controller.rb
module Kinney
  class ClipsController < KinneyController
    include Kinney::Concerns::Controllers::ClipsController
  end
end

app/controllers/kinney/kinney_controller.rb
module Kinney
  class KinneyController < ApplicationController
    helper Kinney::Engine.helpers

    before_filter :gather_topics_for_navigation

    def gather_topics_for_navigation
      @navigation_topics = Topic.with_clips
    end

  end
end

app/controllers/kinney/pages_controller.rb
module Kinney
  class PagesController < KinneyController
    include Kinney::Concerns::Controllers::PagesController
  end
end

app/controllers/kinney/people_controller.rb
module Kinney
  class PeopleController < KinneyController
    include Kinney::Concerns::Controllers::PeopleController
  end
end

app/controllers/kinney/search_controller.rb
module Kinney
  class SearchController < KinneyController
    include Kinney::Concerns::Controllers::SearchController
  end
end

app/controllers/kinney/sitemap_controller.rb
module Kinney
  class SitemapController < KinneyController
    layout nil

    def index
      @people = Person.select([:id, :slug, :created_at, :updated_at])
      @clips  = Clip.all
      headers["Content-Type"] = "text/xml"
      respond_to do |format|
        format.xml{render :layout => false}
      end
    end
  end
end

app/controllers/kinney/topics_controller.rb
module Kinney
  class TopicsController < KinneyController
    include Kinney::Concerns::Controllers::ClipTopicsController
  end
end

app/controllers/kinney/tracker_controller.rb
module Kinney
  class TrackerController < KinneyController

    def track
      if request.xhr?
        data = params["tracker"].dup
        data["session"] = session[:session_id]
        tracker = Tracker.new data.permit(params_permitted)
        tracker.save
        head :ok
      end
    end

    private

    def params_permitted
      [{:seconds => [:start, :end]}, :session, :sessioned, :site, :time, :uuid, :video]
    end

  end
end

app/helpers/kinney/clip_helper.rb
module Kinney
  module ClipHelper
    # FIXME: there has to be a better way to do this so that reloading works!
    # include ::KinneyClipHelper

    def duration_pretty(clip)
      "(#{clip.duration_pretty})" if !clip.duration.blank?
    end


    def download_button(clip)
      link_to(clip.mp4, :class => ['btn', 'btn-lg', 'btn-default'], :id => 'download_mp4') do
        "<i class='icon-arrow-down'></i> #{t 'kinney.clips.show.download_mp4'}".html_safe
      end
    end

    # TODO: once we have VTT for everything change this and make VTT's manditory
    def vtt_button(clip)
      begin
        client = HTTPClient.new
        response = client.head(clip.vtt)
        link_to_options = {:class => 'btn btn-lg btn-default', :id => 'download_vtt'}
        if response.status != 200
          link_to_options.merge!(:style => 'display:none')
        end
        link_to(clip.vtt, link_to_options) do
            "<i class='icon-arrow-down'></i> #{t :download_transcript}".html_safe
          end
      rescue
      end
    end

    def jump_time(timestamp)
      time_parts = timestamp.split(':')
      seconds = time_parts.pop
      minutes = time_parts.pop
      hours   = time_parts.first if !time_parts.blank?
      total_seconds = hours.to_i.hours.seconds
      total_seconds += minutes.to_i.minutes.seconds
      total_seconds += seconds.split('.').first.to_i
    end

    def topic_li_class(topic)
      current_page?(topic_path(topic)) ? 'active' : ''
    end

  end
end

app/views/kinney/pages/_about_text.html.erb
<%= content_for :header do %>
  <h1><%= t 'kinney.pages.about.title' %></h1>
<% end -%>

<p>You can override this template at: app/views/kinney/pages/_about_text.html.erb</p>

<p>
  Some text about Kinney.
</p>

<%= render '/kinney/contact' %>

app/views/kinney/pages/_giving_text.html.erb
<p><%= t 'kinney.pages.giving.meta_description' %></p>

app/views/kinney/pages/_home_catch.html.erb
<%#= render partial: 'home_catch_video_thumbs' %>

app/views/kinney/pages/_home_catch_video_thumbs.html.erb
<div class="container">
  <div class="row">
    <div id="more_clips" class="col-md-12">
      <h2><%= link_to t('kinney.more.video'), clips_path %></h2>
      <div class="row">
        <% @top_pick_clips.each do |clip| %>
          <div class="col-md-3 col-sm-3 col-xs-6 <%= cycle("odd", "even", name: :two_by) -%> <%= cycle("first", 'seconds', 'third', 'fourth', name: :ordinal) %>">
             <%= render :partial => '/kinney/clip_link', :locals => {:clip => clip} %>
          </div>
        <% end -%>
      </ul>
    </div>
  </div>
</div>

app/views/kinney/pages/_home_featured_clip.html.erb
<% if @featured_clip %>
  <h2><%= home_page_featured_clip_title %>
  </h2>
  <%= link_to(@featured_clip, :class => [:thumbnail_video], :id => :featured_video_link) do %>
    <div id="home_video_image">
      <div class="mejs-overlay-button"></div>
      <%= image_tag @featured_clip.png, :alt => @featured_clip.title %>
    </div>
  <% end -%>
<% else -%>
  <p>You currently have no featured clip. Go to the admin interface and create or select a featured clip.</p>
<% end -%>

app/views/kinney/pages/_home_header.html.erb
<%= content_for :header do %>
  <div class="well">
    <h1><%= application_name %></h1>
    <p>Rails Engine for delivering oral history video clips.</p>
    <p>Replace this in app/views/kinney/pages/_home_header.html.erb</p>
  </div>
<% end -%>

app/views/kinney/pages/_home_right_sidebar.html.erb
<div id="topics">
  <%= render '/kinney/video_topics'%>
</div>

app/views/kinney/pages/about.html.erb
<% @title = t('kinney.pages.about.title') %>
<% @meta_description = t('kinney.pages.about.meta_description') %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render '/kinney/pages/about_text' %>
  </div>
</div>

app/views/kinney/pages/giving.html.erb
<% @title = t('kinney.pages.giving.title') %>
<% @meta_description = t('kinney.pages.giving.meta_description') %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1><%= t 'kinney.pages.giving.title' %></h1>
    <%= render '/kinney/pages/giving_text' %>
  </div>
</div>

app/views/kinney/pages/home.html.erb
<% @meta_description = t('kinney.pages.home.meta_description') %>

<%= render '/kinney/pages/home_header' %>

<div class="row">
  <div class="col-md-9">
    <div id="featured_clip">
      <%= render 'home_featured_clip' %>
    </div>
  </div>

  <div class="col-md-3">
    <%= render '/kinney/pages/home_right_sidebar' %>
  </div>

</div>

<% content_for :catch do -%>
  <%= render "home_catch" %>
<% end -%>